/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES.
 * All rights reserved. SPDX-License-Identifier: LicenseRef-NvidiaProprietary
 *
 * NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
 * property and proprietary rights in and to this material, related
 * documentation and any modifications thereto. Any use, reproduction,
 * disclosure or distribution of this material and related documentation
 * without an express license agreement from NVIDIA CORPORATION or its
 * affiliates is strictly prohibited.
 */

#pragma once

#include <cuda_runtime.h>

#include <cstdint>

#include "cascaded/next/primitives/kibi_cascader/kibi_cascader_constants.cuh"
#include "cascaded/next/primitives/kibi_cascader/kibi_cascader_metadata.cuh"
#include "nvcomp_device_common.cuh"

/*
  Kibi-Cascader is a lightweight compression primitive designed to compress input vectors up to
  1KB.

  Users cannot specify a specific encoding to apply, they can only designate a "search space"
  that will be explored during the "plan" stage.

  Larger search spaces can improve payload compression ratio but may generate more metadata, so the
  overall compression ratio may be worse. Compression work generally increases with the search
  space. Decompression does not search; its cost depends on the selected encoding.

  Data Requirements
  - shared_input_buffer must point to a 1KB (256-word) shared-memory buffer
  - input words must use the layout returned by shared_input_word_index
  - bytes beyond input_size_bytes must be padded through the end of the buffer
  - input_size_bytes must report the logical size before padding

  API Requirements
  - all functions must be called collectively by every lane in a converged warp
  - shared_metadata must contain at least get_num_metadata_words<T, SearchSpace>() words in shared memory
  - shared_workspace must contain at least MAX_KC_INPUT_SIZE_BYTES bytes in shared memory
  - plan writes the selected transform into bitpack_input and reports its logical bitpack input size
  - encode must receive the bitpack_input and bitpack input size returned by plan
  - the caller owns any CTA synchronization required before reusing overlapping shared storage

  This is a device-side dispatcher for the typed kibi cascader implementations
*/

namespace nvcomp::cascaded::next::kibi_cascader
{

template <typename T>
struct KibiCascader;

struct KibiCascaderCompressionPlan
{
  uint32_t bitpack_input_size_bytes;
  uint32_t payload_prefix_size_bytes;
  uint32_t payload_size_bytes;
  uint32_t payload_prefix_word;
};

/**
  Selects a compression plan from SearchSpace.
  @tparam T Data type of the input vector
  @tparam SearchSpace Mask indicating which encodings may be considered
  @param shared_input_buffer Padded 1KB input buffer in shared memory
  @param bitpack_input Returns 32 bytes of transformed input per thread in registers
  @param shared_metadata Shared scratch space for metadata generated by the selected plan
  @param shared_workspace Shared workspace used to preserve input and stage selected RLE values
  @param input_size_bytes Logical input size in bytes; must be <= 1024 and aligned to sizeof(T)
  @return The logical bitpack input size and exact payload size
*/
template <typename T, kibi_cascader_optimization_search_space SearchSpace>
inline __device__ KibiCascaderCompressionPlan plan(
  uint32_t *shared_input_buffer,
  uint32_t bitpack_input[KC_WORDS_PER_THREAD],
  uint32_t *shared_metadata,
  uint32_t *shared_workspace,
  const uint32_t input_size_bytes = MAX_KC_INPUT_SIZE_BYTES
)
{
  return KibiCascader<T>::template plan<SearchSpace>(
    shared_input_buffer,
    bitpack_input,
    shared_metadata,
    shared_workspace,
    input_size_bytes
  );
}

/**
  Applies the selected compression plan and writes to the output pointer.
  @tparam T Data type of the input vector
  @tparam SearchSpace Mask indicating which encodings may be considered
  @param bitpack_input 32 bytes of prepared bitpack input per thread, stored in registers
  @param shared_metadata Shared scratch space for metadata generated by the selected plan
  @param output Destination where compressed payload will be written. No alignment requirements.
  @param plan Compression plan returned by plan
*/
template <typename T, kibi_cascader_optimization_search_space SearchSpace>
inline __device__ void encode(
  uint32_t bitpack_input[KC_WORDS_PER_THREAD],
  const uint32_t *shared_metadata,
  uint8_t *output,
  const KibiCascaderCompressionPlan &plan
)
{
  KibiCascader<T>::template encode<SearchSpace>(bitpack_input, shared_metadata, output, plan);
}

/**
  Decodes a compressed payload into per-thread registers.
  @tparam T Data type of the output vector
  @tparam SearchSpace Search space used to encode the payload
  @param payload Compressed payload produced by encode
  @param decoded_output Returns 32 bytes of ordinary type-specific output per thread in registers
  @param shared_metadata Shared metadata deserialized from the compressed representation
  @param shared_workspace Shared workspace available to the selected decoding plan
  @param output_size_bytes Logical decoded size; must be <= 1024 and aligned to sizeof(T)
*/
template <typename T, kibi_cascader_optimization_search_space SearchSpace>
inline __device__ void decode(
  const uint8_t *payload,
  uint32_t decoded_output[KC_WORDS_PER_THREAD],
  const uint32_t *shared_metadata,
  uint32_t *shared_workspace,
  const uint32_t output_size_bytes = MAX_KC_INPUT_SIZE_BYTES
)
{
  KibiCascader<T>::template decode<SearchSpace>(
    payload,
    decoded_output,
    shared_metadata,
    shared_workspace,
    output_size_bytes
  );
}

inline __device__ void write_payload_prefix(uint8_t *payload, const KibiCascaderCompressionPlan &plan)
{
  const uint32_t lane = lane_id();
  if (plan.payload_prefix_size_bytes != 0u && lane * sizeof(uint32_t) < plan.payload_prefix_size_bytes)
  {
    memcpy(payload + lane * sizeof(uint32_t), &plan.payload_prefix_word, sizeof(uint32_t));
  }
}

} // namespace nvcomp::cascaded::next::kibi_cascader
